create login facebook and google logic
DEY-iOS-Team/BalancedDiet pull request #23
Opened 2022-05-12 11:08 UTC by yanpepik

2022-05-12 11:08 UTC, yanpepik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавление логики входа через Google и Facebook](https://trello.com/c/4MF3qXB4/4-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%B8-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-google-%D0%B8-facebook)

2022-05-16 11:56 UTC, vodyan-nucleus requested changes

2022-05-16 11:56 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginInteractor.swift
> +import FacebookCore
Зачем это все тут?

2022-05-16 11:56 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginInteractor.swift
> +// import GoogleSignIn
комменты убрать

2022-05-16 11:56 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginInteractor.swift
> +        presenter.presetInitialData(response: response)
present

2022-05-16 11:56 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginPresenter.swift
> +    func presetInitialData(response: Login.InitialData.Response) {
present

2022-05-16 11:56 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginProtocols.swift
> +    func presetInitialData(response: Login.InitialData.Response)
present

2022-05-16 11:56 UTC, vodyan-nucleus commented on BalancedDiet/Scenes/LogIn/LoginViewController.swift
> +            router.routeToSignUp()
зачем переход в регистрацию?

2022-05-16 13:57 UTC, vodyan-nucleus approved these changes

2022-05-16 13:58 UTC, merged